import "@plaoc/plugin-icon";
// import "@plaoc/plugin-top-bar-android";
// import "@plaoc/plugin-bottom-bar-android";
// import "@plaoc/plugin-status-bar-android";
// import "@plaoc/plugin-dialogs-android";
// import "@plaoc/plugin-keyboard-android";
// import "@plaoc/plugin-top-bar-ios";
// import "@plaoc/plugin-bottom-bar-ios";
// import "@plaoc/plugin-status-bar-ios";
// import "@plaoc/plugin-dialogs-ios";
// import "@plaoc/plugin-keyboard-ios";
import "@plaoc/plugin-top-bar-desktop";
import "@plaoc/plugin-bottom-bar-desktop";
import "@plaoc/plugin-status-bar-desktop";
// import "@plaoc/plugin-dialogs-desktop";
// import "@plaoc/plugin-keyboard-desktop";
