/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bfchain_rust_example_DenoService_IHandleCallback */

#ifndef _Included_org_bfchain_rust_example_DenoService_IHandleCallback
#define _Included_org_bfchain_rust_example_DenoService_IHandleCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
