# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_runtime"
version = "0.73.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/denoland/deno"
description = "Provides the deno runtime library"

[features]
# "fake" feature that allows to generate docs on docs.rs
docsrs = []

[lib]
name = "deno_runtime"
path = "lib.rs"

[[example]]
name = "hello_runtime"
path = "examples/hello_runtime.rs"

[build-dependencies]
deno_broadcast_channel = { version = "0.59.0", path = "../../deno/ext/broadcast_channel" }
deno_console = { version = "0.65.0", path = "../../deno/ext/console" }
deno_core = { version = "0.147.0", path = "../../deno/core" }
deno_crypto = { version = "0.79.0", path = "../../deno/ext/crypto" }
deno_fetch = { version = "0.88.0", path = "../../deno/ext/fetch" }
# deno_ffi = { version = "0.52.0", path = "../../deno/ext/ffi" }
deno_http = { version = "0.59.0", path = "../../deno/ext/http" }
deno_net = { version = "0.57.0", path = "../../deno/ext/net" }
deno_node = { version = "0.2.0", path = "../../deno/ext/node" }
deno_tls = { version = "0.52.0", path = "../../deno/ext/tls" }
deno_url = { version = "0.65.0", path = "../../deno/ext/url" }
deno_web = { version = "0.96.0", path = "../../deno/ext/web" }
deno_webgpu = { version = "0.66.0", path = "../../deno/ext/webgpu" }
deno_webidl = { version = "0.65.0", path = "../../deno/ext/webidl" }
deno_websocket = { version = "0.70.0", path = "../../deno/ext/websocket" }
deno_webstorage = { version = "0.60.0", path = "../../deno/ext/webstorage" }

lzzzz = '1.0'

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[dependencies]
deno_broadcast_channel = { version = "0.59.0", path = "../../deno/ext/broadcast_channel" }
deno_console = { version = "0.65.0", path = "../../deno/ext/console" }
deno_core = { version = "0.147.0", path = "../../deno/core" }
deno_crypto = { version = "0.79.0", path = "../../deno/ext/crypto" }
deno_fetch = { version = "0.88.0", path = "../../deno/ext/fetch" }
# deno_ffi = { version = "0.52.0", path = "../../deno/ext/ffi" }
deno_http = { version = "0.59.0", path = "../../deno/ext/http" }
deno_net = { version = "0.57.0", path = "../../deno/ext/net" }
deno_node = { version = "0.2.0", path = "../../deno/ext/node" }
deno_tls = { version = "0.52.0", path = "../../deno/ext/tls" }
deno_url = { version = "0.65.0", path = "../../deno/ext/url" }
deno_web = { version = "0.96.0", path = "../../deno/ext/web" }
deno_webgpu = { version = "0.66.0", path = "../../deno/ext/webgpu" }
deno_webidl = { version = "0.65.0", path = "../../deno/ext/webidl" }
deno_websocket = { version = "0.70.0", path = "../../deno/ext/websocket" }
deno_webstorage = { version = "0.60.0", path = "../../deno/ext/webstorage" }

atty = "0.2.14"
dlopen = "0.1.8"
encoding_rs = "0.8.31"
filetime = "0.2.16"
fs3 = "0.5.0"
http = "0.2.6"
hyper = { version = "0.14.18", features = ["server", "stream", "http1", "http2", "runtime"] }
libc = "0.2.126"
log = "0.4.16"
lzzzz = '1.0'
netif = "0.1.3"
notify = "=5.0.0-pre.15"
once_cell = "1.10.0"
regex = "1.6.0"
ring = "0.16.20"
serde = { version = "1.0.136", features = ["derive"] }
signal-hook-registry = "1.4.0"
sys-info = "0.9.1"
termcolor = "1.1.3"
tokio = { version = "1.19", features = ["full"] }
uuid = { version = "1.0.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
fwdansi = "1.1.0"
winapi = { version = "0.3.9", features = ["commapi", "knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[target.'cfg(unix)'.dependencies]
nix = "=0.24.2"

[dev-dependencies]
# Used in benchmark
test_util = { path = "../../deno/test_util" }

[package.metadata.docs.rs]
features = ["docsrs"]
