# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
authors.workspace = true
description = "Provides the deno runtime library"
edition.workspace = true
license.workspace = true
name = "deno_runtime"
repository.workspace = true
version = "0.91.0"

[features]
# "fake" feature that allows to generate docs on docs.rs
docsrs = []
# feature that modifies the snapshot to allow extending it
snapshot_from_snapshot = []

[lib]
name = "deno_runtime"
path = "lib.rs"

[[example]]
name = "hello_runtime"
path = "examples/hello_runtime.rs"

[build-dependencies]
deno_broadcast_channel.workspace = true
deno_cache.workspace = true
deno_console.workspace = true
deno_core.workspace = true
deno_crypto.workspace = true
deno_fetch.workspace = true
# deno_ffi.workspace = true
# deno_flash.workspace = true
deno_http.workspace = true
deno_napi.workspace = true
deno_net.workspace = true
deno_node.workspace = true
deno_tls.workspace = true
deno_url.workspace = true
deno_web.workspace = true
deno_webgpu.workspace = true
deno_webidl.workspace = true
deno_websocket.workspace = true
deno_webstorage.workspace = true

lzzzz.workspace = true

[target.'cfg(windows)'.build-dependencies]
winapi.workspace = true
winres.workspace = true

[dependencies]
deno_broadcast_channel.workspace = true
deno_cache.workspace = true
deno_console.workspace = true
deno_core.workspace = true
deno_crypto.workspace = true
deno_fetch.workspace = true
# deno_ffi.workspace = true
# deno_flash.workspace = true
deno_http.workspace = true
deno_napi.workspace = true
deno_net.workspace = true
deno_node.workspace = true
deno_tls.workspace = true
deno_url.workspace = true
deno_web.workspace = true
deno_webgpu.workspace = true
deno_webidl.workspace = true
deno_websocket.workspace = true
deno_webstorage.workspace = true

atty.workspace = true
dlopen.workspace = true
encoding_rs.workspace = true
filetime = "0.2.16"
fs3 = "0.5.0"
http.workspace = true
hyper = {workspace = true, features = ["server", "stream", "http1", "http2", "runtime"]}
libc.workspace = true
log.workspace = true
lzzzz.workspace = true
netif = "0.1.6"
notify.workspace = true
once_cell.workspace = true
regex.workspace = true
ring.workspace = true
serde.workspace = true
signal-hook-registry = "1.4.0"
termcolor = "1.1.3"
tokio.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
fwdansi.workspace = true
ntapi = "0.4.0"
winapi = {workspace = true, features = ["commapi", "knownfolders", "mswsock", "objbase", "psapi", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"]}

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
# Used in benchmark
test_util.workspace = true

[package.metadata.docs.rs]
features = ["docsrs"]
