# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Plaoc-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'SVGKit'
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'UIColor_Hex_Swift'
  pod 'RxSwift'
  pod 'Moya'
  pod 'SSZipArchive'
  pod 'SDWebImage'
  pod 'ZLPhotoBrowser'
  pod 'MagicalRecord'
  # Pods for Plaoc-iOS


  target 'Plaoc-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Plaoc-iOSUITests' do
    # Pods for testing
  end

end
